name: Deploy To Heroku
on:
  workflow_run:
    workflows:
      - "Node Build, Test And Lint CI"
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: master
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success

      - name: Load config vars into .env
        env:
          CONFIG_VARS: ${{ secrets.CONFIG_VARS }}
        run: echo $CONFIG_VARS > .env
      - name: Setup heroku API
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "a.rafaysaleem@gmail.com"
          env_file: ".env"
          
